### ISSUE TITLE
ANY build instructions might help

### ISSUE THREAD

**Issue by ghost** [petermost/FritzBoxCallMonitor#1]
Hello,

in times of home office, I'd really like to try your tool. Unfortunately, I'm not fluent with CMake and your readme offers no help at all.
Until now I found out that I have to 

```
git submodules init
git submodules update
apt install cmake qtbase5-dev qttools5-dev libboost-dev
cmake .
```
Still the build complains:
```
 cmake .
CMake Warning at CppAidKit/CMakeLists.txt:47 (message):
  GoogleTest not found, building without it!


CMake Warning at CppAidKit/CMakeLists.txt:199 (message):
  Boost not found, building without it!


CMake Error at CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source "/usr/src/googletest" which is not an
  existing directory.


-- Configuring incomplete, errors occurred!
```

I can't imagine that I need to compile the tests to get the program. Also, boost in principle is installed, but I can imagine that one of the 1000 sub-libs is missing. I have no way to find out which one.

You are really setting a lot of hurdles to use your program...

**Comment by petermost** [comment]
Hi,

thank you for trying and sorry for your troubles. The easiest solution for now is to install googletest with:

`sudo apt install googletest`

The **warning** :wink:  about `Boost not found` can be ignored. I've setup the C++ AidKit Library to only build certain files if the library dependencies, such as boost, are installed. Obviously that is not yet complete for Google Test and I'm going to fix this.

**Comment by ghost** [comment]
Thanks for your help! Meanwhile, I've commented out everything regarding to tests and got a binary :) I might send you a pull request for the README.md so that others don't suffer my problem.

Thanks for this nice program, it helps me a lot :)

**Comment by petermost** [comment]
> Thanks for this nice program, it helps me a lot :)

:smiley:

**Comment by petermost** [comment]
With the commit 14aa105946d215befc1c9b9baf9024487cfd0133 it shouldn't be necessary any more to having GoogleTest installed.

**Comment by petermost** [comment]
Added build instructions with commit 7fe9ee88cc8bd1649738375bf6d2accee65be53a

**Comment by petermost** [comment]
If you still have problems, then please let me know.
